const { existsSync, readFileSync, writeFileSync } = require("node:fs");
const { randomBytes } = require("node:crypto");

const envPath = ".env";

function secret(length = 48) {
  return randomBytes(length).toString("base64url");
}

function defaultEnv() {
  const postgresPassword = secret(24);
  return `# Generated by npm run setup. Safe defaults for local Docker/development.
# Review and replace these values before exposing the app to the public internet.

# Application
APP_PORT=3000
APP_URL=http://localhost:3000

# Database / cache used by docker-compose service names.
POSTGRES_DB=cdk_delivery_core
POSTGRES_USER=cdk
POSTGRES_PASSWORD=${postgresPassword}
DATABASE_URL=postgresql://cdk:${postgresPassword}@postgres:5432/cdk_delivery_core?schema=public
REDIS_URL=redis://redis:6379

# Required secrets. Generated locally; do not commit .env.
JWT_SECRET=${secret(32)}
APP_SECRET=${secret(32)}

# Optional first admin bootstrap. Change after first login.
ADMIN_EMAIL=admin@example.com
ADMIN_PASSWORD=${secret(18)}

# SMTP can also be configured in the admin UI.
SMTP_HOST=
SMTP_PORT=587
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_FROM_NAME=CDK Delivery Core
SMTP_FROM_EMAIL=no-reply@example.com
SMTP_SECURE=false

# Cloudflare Turnstile can also be configured in the admin UI.
TURNSTILE_SITE_KEY=
TURNSTILE_SECRET_KEY=
`;
}

if (existsSync(envPath)) {
  const current = readFileSync(envPath, "utf8");
  if (current.trim()) {
    console.log(".env already exists; keeping existing local configuration.");
    process.exit(0);
  }
}

writeFileSync(envPath, defaultEnv(), { encoding: "utf8", flag: "w" });
console.log(".env generated with local defaults. Keep this file private.");
